//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2004
        ///1671
        ///1678
        ///1304
        ///1242
        ///1882
        ///1605
        ///1034
        ///1883
        ///1589
        ///1881
        ///1546
        ///1713
        ///1218
        ///1982
        ///1395
        ///1277
        ///1417
        ///1497
        ///1499
        ///1847
        ///1989
        ///1172
        ///1684
        ///1243
        ///1843
        ///1661
        ///1662
        ///1421
        ///1790
        ///1344
        ///1458
        ///1074
        ///1809
        ///1990
        ///1369
        ///1386
        ///1736
        ///1972
        ///1634
        ///1229
        ///1123
        ///1870
        ///1595
        ///1934
        ///1399
        ///1732
        ///1545
        ///1208
        ///368
        ///1907
        ///1143
        ///443
        ///1929
        ///1965
        ///1872
        ///1738
        ///1967
        ///997
        ///1473
        ///1041
        ///1991
        ///1868
        ///1180
        ///1409
        ///1379
        ///1568
        ///1163
        ///1869
        ///1391
        ///1956
        ///1249
        ///1505
        ///351
        ///2001
        ///462
        ///1219
        ///1731
        ///1802
        ///1798
        ///1626
        ///1438
        ///1099
        ///1477
        ///1980
        ///1708
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Year2020Day01 {
            get {
                return ResourceManager.GetString("Year2020Day01", resourceCulture);
            }
        }
    }
}
