//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2004
        ///1671
        ///1678
        ///1304
        ///1242
        ///1882
        ///1605
        ///1034
        ///1883
        ///1589
        ///1881
        ///1546
        ///1713
        ///1218
        ///1982
        ///1395
        ///1277
        ///1417
        ///1497
        ///1499
        ///1847
        ///1989
        ///1172
        ///1684
        ///1243
        ///1843
        ///1661
        ///1662
        ///1421
        ///1790
        ///1344
        ///1458
        ///1074
        ///1809
        ///1990
        ///1369
        ///1386
        ///1736
        ///1972
        ///1634
        ///1229
        ///1123
        ///1870
        ///1595
        ///1934
        ///1399
        ///1732
        ///1545
        ///1208
        ///368
        ///1907
        ///1143
        ///443
        ///1929
        ///1965
        ///1872
        ///1738
        ///1967
        ///997
        ///1473
        ///1041
        ///1991
        ///1868
        ///1180
        ///1409
        ///1379
        ///1568
        ///1163
        ///1869
        ///1391
        ///1956
        ///1249
        ///1505
        ///351
        ///2001
        ///462
        ///1219
        ///1731
        ///1802
        ///1798
        ///1626
        ///1438
        ///1099
        ///1477
        ///1980
        ///1708
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Year2020Day01 {
            get {
                return ResourceManager.GetString("Year2020Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14-15 v: vdvvvvvsvvvvvfpv
        ///3-11 k: kkqkkfkkvkgfknkx
        ///6-10 j: jjjjjjjjjj
        ///5-10 s: nskdmzwrmpmhsrzts
        ///13-15 v: vvvvvvkvvvvjzvv
        ///11-13 h: hhhhhbhhhhdhhh
        ///14-15 r: rrrrrrrrzrrrrrtl
        ///2-9 c: llhctjgbz
        ///13-15 s: ssssxssssssssjs
        ///6-8 c: lccccqcc
        ///8-9 n: nnnnnmnch
        ///4-5 n: jnnnmmpxngbrknzb
        ///4-7 n: knlnqnnndnn
        ///13-18 g: ggggggggnggggggggggp
        ///5-6 m: mmmmgm
        ///5-10 l: lvlllglllpll
        ///7-12 z: pszgzqzzzzkw
        ///1-2 j: pjjqw
        ///15-16 n: nnnnnnnnnnnnnnpn
        ///8-14 z: mzzzjzzzzhzzzztznzz
        ///5-19 q: rnsdfgkqlqjdvrmtsqqh
        ///1-5 f: ffffff
        ///4-5 h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Year2020Day02 {
            get {
                return ResourceManager.GetString("Year2020Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#.#....##.......#..........#..
        ///...#...........##...#..#.......
        ///#.####......##.#...#......#.#..
        ///##.....#.#.#..#.#............#.
        ///##.....#....#.........#...##...
        ///###..#.....#....#..............
        ///..........#..#.#..#.#....#.....
        ///##.....#....#.#...#.##.........
        ///#...#......#....##....#..#.#...
        ///.##.##...#....##..#.#.....#...#
        ///.....#.#..........##.#........#
        ///.##..................#..#..##.#
        ///#.#..........##....#.####......
        ///.#......#.#......#.........#...
        ///#....#..##.##..##........#.#...
        ///##..#.##..#...#.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Year2020Day03 {
            get {
                return ResourceManager.GetString("Year2020Day03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byr:1937
        ///eyr:2030 pid:154364481
        ///hgt:158cm iyr:2015 ecl:brn hcl:#c0946f cid:155
        ///
        ///cid:279
        ///eyr:2029
        ///pid:675014709 ecl:amb
        ///byr:1985 hgt:179in hcl:z iyr:2025
        ///
        ///iyr:2011 hgt:181cm hcl:#341e13 pid:282499883 byr:1953
        ///eyr:2023
        ///ecl:brn
        ///
        ///eyr:2040 iyr:1984 pid:2371396209 byr:1951 cid:283 hgt:164cm
        ///hcl:#623a2f
        ///
        ///iyr:2014 byr:1966 hgt:153cm pid:900693718 eyr:2020 ecl:gry hcl:#866857
        ///
        ///eyr:2020 hgt:162cm
        ///byr:1939 pid:900852891 iyr:2020
        ///ecl:oth hcl:#b6652a
        ///
        ///iyr:1956
        ///hcl:2385ac
        ///hgt:167in
        ///ecl:#9b82e8
        ///e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Year2020Day04 {
            get {
                return ResourceManager.GetString("Year2020Day04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBFFFFFLLL
        ///FFBFFFFRRR
        ///FFFBBBBLRL
        ///FBFFBBFLLL
        ///FFFBFBBLLL
        ///FBFFFFBRLR
        ///BFFBBFBLLL
        ///FBFBFFBLLL
        ///BFFFBBBRLL
        ///FBFBBFBRLR
        ///BFBFFFBRLR
        ///FFFBBFFRLR
        ///FFFFFBFRRR
        ///FBFBBBFRRL
        ///FBFBBFBRRR
        ///FBFBBBFLRR
        ///BBFFFBBRLL
        ///FBBBBBFRLL
        ///FBFFFFBLLR
        ///FBFFFFFLRR
        ///FBFBFFBLRR
        ///FBFBFBBRRL
        ///FFFFBFFRRL
        ///FFFFBBFLRR
        ///BFFBBFBRLR
        ///BBFFFFFRLR
        ///FFBFBBBRLL
        ///FFBFBBBLRL
        ///FBFFFBBLLL
        ///FFFFBBFRLR
        ///FBFBBFFLLR
        ///FBBFFBFRLL
        ///BFFFBFBLLR
        ///FBFFBBBLLL
        ///FFFFBBBLRR
        ///FFBFFBFLLL
        ///BFBFBFBRRL
        ///BFBFFFBRRL
        ///FBFBFBFLLL
        ///FBBBBFFRRR
        ///FBFFBFBRRR
        ///BBFFFFFRRL
        ///BFFFFFFL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Year2020Day05 {
            get {
                return ResourceManager.GetString("Year2020Day05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nefaym
        ///eynamf
        ///eafnmy
        ///afnmey
        ///
        ///zmd
        ///alo
        ///ekvrtpyuqi
        ///hwmc
        ///szgah
        ///
        ///y
        ///mzqys
        ///ycsq
        ///yrtxvnkdglj
        ///
        ///egubpzyrhlojkixfn
        ///hyifblockgenrzjxp
        ///zxgbkohlpyfjinre
        ///rzolbfihpkxnygje
        ///
        ///wvjoehlkxnyz
        ///evwkobnhy
        ///nerkyowgv
        ///taypknsdovmuwice
        ///qjvknewory
        ///
        ///ncypkuxsizla
        ///ndjoiqhetrgmwfvb
        ///
        ///tfhnk
        ///kmnftzh
        ///hkntf
        ///nftkh
        ///
        ///wj
        ///w
        ///w
        ///wq
        ///w
        ///
        ///jzaw
        ///jzw
        ///
        ///gysdxblojkvnmr
        ///khymldnxgtbvirj
        ///bydgmxwjvrkfln
        ///lykvumdnrxbjg
        ///
        ///xce
        ///xec
        ///xec
        ///cex
        ///
        ///lacbwdzjofymieug
        ///qpbhtnywsluirgjaxkfm
        ///
        ///orzpamlyckgwhjidnq
        ///myeqhzijgkdoxwprcv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Year2020Day06 {
            get {
                return ResourceManager.GetString("Year2020Day06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to muted lavender bags contain 5 dull brown bags, 4 pale maroon bags, 2 drab orange bags.
        ///plaid aqua bags contain 1 posh violet bag, 5 pale yellow bags, 4 bright salmon bags.
        ///wavy lime bags contain 3 vibrant indigo bags, 1 posh gray bag.
        ///pale coral bags contain 5 mirrored olive bags, 2 posh salmon bags.
        ///faded chartreuse bags contain 1 plaid blue bag, 4 clear salmon bags, 5 muted teal bags.
        ///vibrant indigo bags contain 4 pale red bags, 1 vibrant violet bag.
        ///vibrant salmon bags contain 1 dull crimson bag, 5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Year2020Day07 {
            get {
                return ResourceManager.GetString("Year2020Day07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light red bags contain 1 bright white bag, 2 muted yellow bags.
        ///dark orange bags contain 3 bright white bags, 4 muted yellow bags.
        ///bright white bags contain 1 shiny gold bag.
        ///muted yellow bags contain 2 shiny gold bags, 9 faded blue bags.
        ///shiny gold bags contain 1 dark olive bag, 2 vibrant plum bags.
        ///dark olive bags contain 3 faded blue bags, 4 dotted black bags.
        ///vibrant plum bags contain 5 faded blue bags, 6 dotted black bags.
        ///faded blue bags contain no other bags.
        ///dotted black bags contain no othe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Year2020Day07Test {
            get {
                return ResourceManager.GetString("Year2020Day07Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shiny gold bags contain 2 dark red bags.
        ///dark red bags contain 2 dark orange bags.
        ///dark orange bags contain 2 dark yellow bags.
        ///dark yellow bags contain 2 dark green bags.
        ///dark green bags contain 2 dark blue bags.
        ///dark blue bags contain 2 dark violet bags.
        ///dark violet bags contain no other bags..
        /// </summary>
        internal static string Year2020Day07Test2 {
            get {
                return ResourceManager.GetString("Year2020Day07Test2", resourceCulture);
            }
        }
    }
}
